### ISSUE TITLE
Error code -8001

### ISSUE THREAD

**Issue by shoutbomb** [RCPL/Polaris-API-PHP-Class#3]
Hello,
I am a third party supporting a library. Using your example.php to validate some changes I would like to make.  Providing all the 'client' parameters for a typical staff user, I encountered the following when running step 2 "Get a list of hold requests for a customer using PatronHoldRequestsGet".

> $response	stdClass	
> 	AccessSecret	null	
> 	AccessToken	null	
> 	AuthExpDate	null	
> 	BranchID	0	
> 	ErrorMessage	null	
> 	PAPIErrorCode	-8001	
> 	PolarisUserID	0	

Why was there an error when I was able to complete step 1.

Thanks...

**Comment by attheshow** [comment]
According to [the Polaris API documentation](http://developer.polarislibrary.com/documentation.aspx), the -8001 error indicates "Polaris user is not permitted".

**Comment by shoutbomb** [comment]
AccessSecret | SimpleXMLElement
AccessToken | SimpleXMLElement
AuthExpDate | SimpleXMLElement
BranchID | 0
ErrorMessage | Unexpected end of   file. Following elements are not closed: Password, AuthenticationData. Line   2, position 34.
PAPIErrorCode | -1
PolarisUserID | 0

AccessSecret | SimpleXMLElement
AccessToken | SimpleXMLElement
AuthExpDate | SimpleXMLElement
BranchID | 0
ErrorMessage | SimpleXMLElement
PAPIErrorCode | -8001
PolarisUserID | 0

This was caused by the "&" and a "comma" in the generated password provided to me.
